version: '2'

services:
  unifi:
    container_name: unifi
    image: "jacobalberty/unifi"
    network_mode: "host"
    restart: always
    environment:
      - TZ=Europe/Brussels
      - RUNAS_UID0=false
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8080:8080/tcp" # Device/ controller comm.
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp" # HTTP portal redirection
      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery
    volumes:
      - unifi_data:/unifi
      - unifi_runtime:/var/run/unifi
      
  traefik:
    container_name: traefik
    image: traefik
    command: --api --docker --docker.domain=docker.home
    restart: always
    networks:
      - container_network
    ports:
      - "80:80"
#      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_tmp:/tmp
    labels:
      - traefik.frontend.rule=PathPrefixStrip:/traefik/
      - traefik.port=8080

  portainer:
    container_name: portainer
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    environment:
      - TZ=Europe/Brussels
      - RUNAS_UID0=false
    networks:
      - container_network
#    ports:
#      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - traefik.frontend.rule=PathPrefixStrip:/portainer/
      - traefik.port=9000

  duplicacy:
    container_name: duplicacy
    image: saspus/duplicacy-web
    hostname: 'docker.home'
    restart: always
    environment:
      - TZ=Europe/Brussels
      - USR_ID=0
      - GRP_ID=0
      - DWE_PASSWORD=frostlock
    networks:
      - container_network
#    ports:
#      - "3875:3875/tcp"
    volumes:
      - duplicacy_data:/config
      - duplicacy_log:/logs
      - duplicacy_cache:/cache
      - /var/lib/docker/volumes/:/backuproot:ro
    labels:
      - traefik.rule1.frontend.rule=PathPrefixStrip:/duplicacy/
      - traefik.rule2.frontend.rule=PathPrefix:/start_stop_schedule,/swap_jobs,/verify_password,/get_backup_status,/get_schedule_status,/list_repositories,/list_revisions,/add_job,/delete_repository,/lookup_schedule,/save_schedule,/get_patterns,/save_patterns,/save_repository,/start_stop_backup,/get_schedule_email,/set_schedule_email,/test_schedule_email,/delete_schedule,/list_files,/get_listing_status,/update_listing_session,/list_restore_directory,/list_local_directory,/start_restore,/get_restore_status,/show_log
      - traefik.port=3875

  cadvisor:
    container_name: cadvisor
    image: google/cadvisor:latest
    restart: always
    environment:
      - TZ=Europe/Brussels
    networks:
      - container_network
#    ports:
#      - "8084:8080/tcp"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    labels:
      - traefik.frontend.rule=PathPrefixStrip:/cadvisor/
      - traefik.port=8080

volumes:
  traefik_tmp:
  portainer_data:
  unifi_data:
  unifi_runtime:
  duplicacy_data:
  duplicacy_log:
  duplicacy_cache:

networks:
  container_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24
