# Use root as database user, password set below
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sengir00

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
    environment:
      - ADMINER_DESIGN=galkaev
